### ISSUE TITLE
fix \scr{R}

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/publications#11]
pubparse replaces curly brackets by nothing (no idea why, probably a good reason), and hence some latex formatting is broken. for the combinat list, the "\scr{R}" probably needs to be replaced by `&#x211b;` to get the &#x211b;.

**Comment by nthiery** [comment]
Just a side comment: it would be nice if pubparse did support Mathscinet entries as is.

**Comment by haraldschilly** [comment]
fixed in 031a1a5b546eeb430
