### ISSUE TITLE
add "Symbolic and Numerical Analysis in General Relativity with Open  Source Computer Algebra Systems"

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/publications#114]
Tolga Birkandan, Ceren Guzelgun, Elif Sirin, Mustafa Can Uslu, 
"Symbolic and Numerical Analysis in General Relativity with Open 
Source Computer Algebra Systems", General Relativity and Gravitation 
51, 4 (2019) (arXiv: 1703.09738 [gr-qc])

https://link.springer.com/article/10.1007/s10714-018-2486-x

**Comment by dimpase** [comment]
Are these being added to a bibtex file?

**Comment by haraldschilly** [comment]
well, I don't have the capacity to deal with all this. I just make sure they're collected here and hopefully someone will look them all up and add them to the bin file.

**Comment by dimpase** [comment]
here is bibtex for it, from AMS' MathSciNet
```
@article {MR3881305,
    AUTHOR = {Birkandan, Tolga and G\"{u}zelg\"{u}n, Ceren and \c{S}irin, Elif and Can
              Uslu, Mustafa},
     TITLE = {Symbolic and numerical analysis in general relativity with
              open source computer algebra systems},
   JOURNAL = {Gen. Relativity Gravitation},
  FJOURNAL = {General Relativity and Gravitation},
    VOLUME = {51},
      YEAR = {2019},
    NUMBER = {1},
     PAGES = {Paper No. 4, 22},
      ISSN = {0001-7701},
   MRCLASS = {83-04},
  MRNUMBER = {3881305},
       DOI = {10.1007/s10714-018-2486-x},
       URL = {https://doi.org/10.1007/s10714-018-2486-x},
}
```

Do I understand it right it also needs `journaltitle=...` ? Weird.

**Comment by haraldschilly** [comment]
yes

**Comment by haraldschilly** [comment]
yes
