### ISSUE TITLE
Add "How to cite?" information to FAQ

### ISSUE THREAD

**Issue by AlexisPrel** [sagemath/publications#123]
It is common for academic-oriented software to feature an "how to cite" page on their website.
Unless I am mistaken, this is not the case for SageMath. There is no entry about it in the FAQ either, nor the README.

Where can I find this information?
Wouldn't it be worth adding to the FAQ, manual or website?

**Comment by AlexisPrel** [comment]
I am seeing only now that this issue [has been brought up before](https://trac.sagemath.org/ticket/30717).

Answer to my first equation, in case someone reaches github before the wiki:
https://wiki.sagemath.org/Publications_using_SageMath

**Comment by haraldschilly** [comment]
at the bottom of https://www.sagemath.org/library-publications.html is a note about this
