### ISSUE TITLE
Add Math Mag scheduling paper from 2024

### ISSUE THREAD

**Issue by kcrisman** [sagemath/publications#154]
The paper by Jeff Denny, *Schedules and Waitlists and Integer Programs, Oh My!* https://www.tandfonline.com/doi/full/10.1080/0025570X.2023.2284419 mentions using (but doesn't cite) Sage - interestingly, using GLPK, not the usual Sage usage but good that we have those interfaces!

**Comment by AdityaK1729** [comment]
Hi I recently fixed one issue in this repo, got a bit busy lately but can do some of these in 1-2 days
Do I take this one?

**Comment by haraldschilly** [comment]
@AdityaK1729 you can do all the [new paper](https://github.com/sagemath/publications/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+paper%22) issues. Everyone will be happy if someone digs through them :pick:

**Comment by AdityaK1729** [comment]
I was thinking about that, does fixing all issues in same PR ok for you?

**Comment by haraldschilly** [comment]
Yes, just mention the tickets in the first message of the PR in a bullet list, like `* fixes #123`

Then, when the PR is merged, those tickets will be closed automatically and have proper references☺️

**Comment by AdityaK1729** [comment]
Hey, I am fixing all this issues today, can you tell me the rough format in which I add these to bibiliography-sage.bib
