### ISSUE TITLE
add "Infinite families of standard Cappell-Shaneson spheres"

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/publications#155]
> I have cited SageMath in my paper, https://doi.org/10.48550/arXiv.2404.05096, so I would like you to write my paper information on the web page, https://www.sagemath.org/library-publications.html.

```
@misc{iwaki2024infinite,
      title={Infinite families of standard Cappell-Shaneson spheres}, 
      author={Kazunori Iwaki},
      year={2024},
      eprint={2404.05096},
      archivePrefix={arXiv},
      primaryClass={math.GT}
}
```

**Comment by AdityaK1729** [comment]
Can I do this as my first issue

**Comment by haraldschilly** [comment]
Cool. Basically you have to add it to `bibliography-sage.bib` and check that the key is unique.

**Comment by AdityaK1729** [comment]
nice, just to make sure by key you mean this part 'iwaki2024infinite' right?

**Comment by haraldschilly** [comment]
Yes, because if someone downloads the bib file, and references it in their latex document, it should work fine. Usually, they're derived from names, year and authors in some way, such that they're unique. If they're not, it's just an inconvenience.

When you push the PR, please let me know. I think a build action should run to confirm your change is working – otherwise I'll activate it.

**Comment by AdityaK1729** [comment]
I have added a PR please check
