### ISSUE TITLE
Add "The Riemann Hypothesis" book from MAA

### ISSUE THREAD

**Issue by kcrisman** [sagemath/publications#29]
[This book](http://www.maa.org/press/ebooks/the-riemann-hypothesis) mentions Sage in several places for computing (as well as mentioning the Stein/Mazur book, which apparently wasn't finished when this was published).

**Comment by williamstein** [comment]
Thanks for the heads up.  How do you know about the content of that book?  Did you buy a print version, or see it at the JMM or something?

**Comment by kcrisman** [comment]
> Thanks for the heads up. How do you know about the content of that book?
> Did you buy a print version, or see it at the JMM or something?
>
I bought a print version at the JMM, because it seemed pretty relevant for
my NT class (right level and about RH).   It was actually originally aimed
at high schoolers in the Netherlands, to get them excited about
higher-level mathematics - a good choice!  Maybe we need a book about BSD
at the same level ;-)
