### ISSUE TITLE
Add Sage book "Einführung in die computerorientierte Mathematik mit Sage"

### ISSUE THREAD

**Issue by kcrisman** [sagemath/publications#32]
Apparently a new Sage book in German.

https://groups.google.com/forum/#!topic/sage-edu/ENxPHHE0zFE

http://www.springer.com/de/book/9783658104528

http://www.math.uni-frankfurt.de/~theobald/ecms/

**Comment by haraldschilly** [comment]
Is this this one: https://github.com/sagemath/publications/blob/master/bibliography-sage.bib#L4352 ?

**Comment by kcrisman** [comment]
Yup, sorry for the noise - I had only heard of it via the sage-edu list, unless my memory is really failing, which it might be...
