### ISSUE TITLE
\mathbb{Z} does not display well on the webpage - mathjax?

### ISSUE THREAD

**Issue by dimpase** [sagemath/publications#41]
see entry 301. Needs some stuff I don't know in pubparse.py
Perhaps, just hook mathjax on!

**Comment by haraldschilly** [comment]
similarly, `\mathbb{Q}` … mentioned in https://github.com/sagemath/publications/pull/129#issuecomment-1050751548

**Comment by haraldschilly** [comment]
I'm closing this. For now this is just a simple replacement table. I'll make a ticket to use katex to render all this on the fly during compilation.
