### ISSUE TITLE
MANUAL DE CÁLCULO CIENTÍFICO EN SAGEMATH

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/publications#52]
http://oaq.epn.edu.ec/index.php/publicaciones/publicaciones-varios/160-calculo-cientifico-en-sagemath-con-enfasis-en-sagemanifolds

**Comment by kcrisman** [comment]
> Closed #52 <https://github.com/sagemath/publications/issues/52> via
> 87c7b9a
> <https://github.com/sagemath/publications/commit/87c7b9a8ade9743651105292d1e3ea21ef2baddb>
> .
>
>

Do you think a link to this should be added to the "documentation" page?
Do we even have that list any more of tutorial/reference resources?  (It
was on the old website but might not have survived the transition to
doc.sagemath.org, it was better organized that that site's first page, for
sure.)

**Comment by haraldschilly** [comment]
I think you mean the help page: http://www.sagemath.org/help.html which is still there as before

**Comment by kcrisman** [comment]
Oh yeah!  Maybe that page needs some TLC, eh?

**Comment by haraldschilly** [comment]
well, I would say it doesn't hurt. of all pages, it's visitation rank is 8 ...

**Comment by kcrisman** [comment]
well, I would say it doesn't hurt. of all pages, it's visitation rank is 8
> ...
>
>
wow
